-- the first script for migration

CREATE TABLE Book(
	b_id SERIAL PRIMARY KEY,
	b_title VARCHAR(50) NOT NULL,
	b_author VARCHAR(50),
	b_copies INT
);

CREATE TABLE Student(
	s_id SERIAL PRIMARY KEY,
	s_name VARCHAR(50) NOT NULL,
	s_email VARCHAR(50),
	s_pass VARCHAR(50)
	
);

CREATE TABLE "user"(
    id SERIAL primary key,
    fullname varchar(50),
    isAdmin boolean ,
    password varchar(50),
    username varchar(50)
);


CREATE TABLE ADMIN(
	u_id SERIAL PRIMARY KEY,
	u_name VARCHAR(50),
	u_mail VARCHAR(50),
	u_pass VARCHAR(50)
);
create table Article (
    id bigint generated by default as identity,
    content varchar(5000),
    postedAt timestamp,
    title varchar(255),
    primary key (id)
);

create table Article_authorIds (
    Article_id bigint not null,
    authorIds bigint
);
    
alter table Article_authorIds 
add constraint FK_f9ivk719aqb0rqd8my08loev7 
foreign key (Article_id) 
references Article;